---
- id: minimum-changes
  name: Minimum Changes
  description: This hook checks for a minimum number of line changes against git diff
  entry: minimum-changes
  language: python
  pass_filenames: True
  types: [text]
- id: validate-bes
  name: Validate BigFix BES Files
  description: This hook validates BigFix BES XML Files
  entry: validate-bes
  language: python
  pass_filenames: True
  types: [text]
  files: \.(bes|ojo)$
- id: verify-files-contain-entry
  name: Verify Files Contain Entry
  description: This hook validates that a file has a regex match or group within a reference file
  entry: verify-files-contain-entry
  language: python
  pass_filenames: True
  types: [text]
- id: verify-files-contain-pattern
  name: Verify Files Contain Pattern
  description: This hook validates that a file has a regex match or group within a reference file
  entry: verify-files-contain-pattern
  language: python
  pass_filenames: True
  types: [text]
- id: verify-files-are-ascii
  name: Verify Files Are ASCII
  description: This hook validates that a file has only ASCII contents
  entry: verify-files-are-ascii
  language: python
  pass_filenames: True
  types: [text]
