---
name: test_build

on:
  push:
    paths:
      - "**.py"
      - "setup.cfg"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"
      - ".github/workflows/tag_and_release.yaml"
  pull_request:
    paths:
      - "**.py"
      - "setup.cfg"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"
      - ".github/workflows/tag_and_release.yaml"

jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test python import from src
        shell: bash
        run: python -c "import pre_commit_hooks; print(pre_commit_hooks.__version__)"
      - name: Install build tools
        run: pip install setuptools wheel build
      - name: Get version from setup.cfg
        run: python setup.py --version
      - name: Run build
        run: python3 -m build
      - name: Get Wheel File Path
        id: getwheelfile
        shell: bash
        run: echo "::set-output name=wheelfile::$(find "dist" -type f -name "*.whl")"
      - name: Test pip install of wheel
        shell: bash
        run: pip install $(find "dist" -type f -name "*.whl")
      - name: Test python import
        shell: bash
        run: python -c "import pre_commit_hooks; print(pre_commit_hooks.__version__)"
      - name: Test pre-commit hook invoke
        shell: bash
        run: python -c "import pre_commit_hooks.git_clean; pre_commit_hooks.git_clean.main()"
      - name: Test pre-commit hook invoke
        shell: bash
        run: python -c "import pre_commit_hooks.minimum_changes; pre_commit_hooks.minimum_changes.main()"
      - name: Test pre-commit hook invoke
        shell: bash
        run: python -c "import pre_commit_hooks.regex_search_filter_replace; pre_commit_hooks.regex_search_filter_replace.main()"
      - name: Test pre-commit hook invoke
        shell: bash
        run: python -c "import pre_commit_hooks.revert_missing_change; pre_commit_hooks.revert_missing_change.main()"
      - name: pip install of pre-commit
        shell: bash
        run: pip install pre-commit
      - name: pre-commit try-repo
        shell: bash
        run: pre-commit try-repo . --files test/example.test_file test/example-test.bes
